#!/usr/bin/env python3
"""Train DaniBot directly from a FEN/Move CSV dataset.

The CSV is expected to contain columns:
  - FEN
  - Move

Move can be SAN or UCI. By default, the script auto-detects the format.
The current project CSVs generated by scripts/pgn_to_fen_move_csv.py are SAN,
so they work out of the box.

This trainer is designed for large CSV files and streams data chunk-by-chunk,
so it does not need to load the full dataset into memory.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
import time
from contextlib import nullcontext
from pathlib import Path
from typing import Optional

import chess
import numpy as np
import torch
import torch.nn as nn

from ArchiveAlpha import HAS_CYTHON_BATCH, cy_encode_board_batch, encode_board_array
from ChessNet import ChessNet


PROJECT_ROOT = Path(__file__).resolve().parent
CHECKPOINTS_DIR = PROJECT_ROOT / "checkpoints"
UCI_MOVE_RE = re.compile(r"^[a-h][1-8][a-h][1-8][qrbn]?$")


def detect_default_csv() -> Path:
    candidates = [
        PROJECT_ROOT / "lichess_2200plus_fen_move.csv",
        PROJECT_ROOT / "lichess_2500plus_fen_move.csv",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Train DaniBot from a streamed FEN/Move CSV dataset."
    )
    parser.add_argument("--csv", type=Path, default=detect_default_csv(), help="Input FEN/Move CSV path")
    parser.add_argument("--mapping", type=Path, default=PROJECT_ROOT / "move_mapping.json", help="move_mapping.json path")
    parser.add_argument("--model-path", type=Path, default=PROJECT_ROOT / "danibot.pth", help="Output DaniBot model path")
    parser.add_argument(
        "--checkpoint-path",
        type=Path,
        default=CHECKPOINTS_DIR / "danibot_csv_resume.pt",
        help="Resume checkpoint path",
    )
    parser.add_argument("--epochs", type=int, default=5, help="Number of epochs")
    parser.add_argument("--batch-size", type=int, default=None, help="Mini-batch size")
    parser.add_argument("--chunk-size", type=int, default=8192, help="CSV samples encoded per chunk")
    parser.add_argument("--lr", type=float, default=1e-3, help="Learning rate")
    parser.add_argument("--weight-decay", type=float, default=1e-5, help="Adam weight decay")
    parser.add_argument("--grad-clip", type=float, default=1.0, help="Gradient clipping norm; <=0 disables clipping")
    parser.add_argument(
        "--move-format",
        choices=["auto", "san", "uci"],
        default="auto",
        help="How to parse the Move column",
    )
    parser.add_argument(
        "--value-weight",
        type=float,
        default=0.1,
        help="Weight for zero-target value regularization",
    )
    parser.add_argument(
        "--max-rows",
        type=int,
        default=None,
        help="Optional limit of valid training rows per epoch (useful for smoke tests)",
    )
    parser.add_argument(
        "--checkpoint-every-chunks",
        type=int,
        default=50,
        help="Save checkpoint/model every N chunks",
    )
    parser.add_argument(
        "--progress-every-chunks",
        type=int,
        default=10,
        help="Print training progress every N chunks",
    )
    parser.add_argument("--encoding", default="utf-8", help="CSV file encoding")
    parser.add_argument("--resume", dest="resume", action="store_true", help="Resume from checkpoint if it exists")
    parser.add_argument("--no-resume", dest="resume", action="store_false", help="Ignore resume checkpoint")
    parser.add_argument("--amp", dest="amp", action="store_true", help="Enable AMP on CUDA")
    parser.add_argument("--no-amp", dest="amp", action="store_false", help="Disable AMP")
    parser.add_argument("--compile", dest="compile_model", action="store_true", help="Enable torch.compile when available")
    parser.add_argument("--no-compile", dest="compile_model", action="store_false", help="Disable torch.compile")
    parser.set_defaults(resume=True, amp=None, compile_model=False)
    return parser


def choose_device() -> torch.device:
    if torch.backends.mps.is_available():
        return torch.device("mps")
    if torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")


def choose_batch_size(device: torch.device, explicit: Optional[int]) -> int:
    if explicit is not None:
        return explicit
    if device.type == "mps":
        return 384
    if device.type == "cuda":
        return 256
    return 128


def choose_amp(device: torch.device, explicit: Optional[bool]) -> bool:
    if explicit is not None:
        return explicit
    return device.type == "cuda"


def load_move_mapping(mapping_path: Path) -> tuple[list[str], dict[str, int]]:
    with mapping_path.open("r", encoding="utf-8") as f:
        move_list = json.load(f)
    return move_list, {uci: idx for idx, uci in enumerate(move_list)}


def parse_csv_move(board: chess.Board, move_text: str, move_format: str) -> chess.Move:
    move_text = move_text.strip()

    if move_format in ("auto", "uci") and UCI_MOVE_RE.match(move_text):
        move = chess.Move.from_uci(move_text)
        if move in board.legal_moves:
            return move
        if move_format == "uci":
            raise ValueError(f"Illegal UCI move for board: {move_text}")

    if move_format in ("auto", "san"):
        try:
            return board.parse_san(move_text)
        except ValueError:
            if move_format == "san":
                raise

    raise ValueError(f"Could not parse move '{move_text}' as {move_format}")


def validate_csv_columns(fieldnames) -> None:
    required = {"FEN", "Move"}
    actual = set(fieldnames or [])
    if not required.issubset(actual):
        missing = ", ".join(sorted(required - actual))
        print(f"CSV is missing required columns: {missing}", file=sys.stderr)
        raise SystemExit(1)


def build_chunk_tensors(boards: list[chess.Board], labels: list[int]) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    if HAS_CYTHON_BATCH:
        x_np = cy_encode_board_batch(boards)
    else:
        x_np = np.stack([encode_board_array(board) for board in boards], axis=0)

    y_np = np.asarray(labels, dtype=np.int64)
    v_np = np.zeros(len(labels), dtype=np.float32)
    return torch.from_numpy(x_np), torch.from_numpy(y_np), torch.from_numpy(v_np)


def iterate_csv_chunks(
    csv_path: Path,
    move2idx: dict[str, int],
    chunk_size: int,
    move_format: str,
    encoding: str,
    max_rows: Optional[int],
    skip_valid_rows: int,
):
    stats = {
        "csv_rows_seen": 0,
        "valid_rows_seen": 0,
        "invalid_fen": 0,
        "invalid_move": 0,
        "unmapped_move": 0,
    }

    with csv_path.open("r", newline="", encoding=encoding, errors="replace") as f:
        reader = csv.DictReader(f)
        validate_csv_columns(reader.fieldnames)

        boards: list[chess.Board] = []
        labels: list[int] = []

        for row in reader:
            stats["csv_rows_seen"] += 1

            fen = (row.get("FEN") or "").strip()
            move_text = (row.get("Move") or "").strip()
            if not fen or not move_text:
                stats["invalid_move"] += 1
                continue

            try:
                board = chess.Board(fen)
            except ValueError:
                stats["invalid_fen"] += 1
                continue

            try:
                move = parse_csv_move(board, move_text, move_format)
            except ValueError:
                stats["invalid_move"] += 1
                continue

            move_idx = move2idx.get(move.uci())
            if move_idx is None:
                stats["unmapped_move"] += 1
                continue

            stats["valid_rows_seen"] += 1

            if stats["valid_rows_seen"] <= skip_valid_rows:
                continue

            if max_rows is not None and (stats["valid_rows_seen"] - skip_valid_rows) > max_rows:
                break

            boards.append(board)
            labels.append(move_idx)

            if len(labels) >= chunk_size:
                yield build_chunk_tensors(boards, labels), stats.copy()
                boards = []
                labels = []

        if labels:
            yield build_chunk_tensors(boards, labels), stats.copy()


def save_training_state(
    checkpoint_path: Path,
    model_path: Path,
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    scheduler,
    next_epoch: int,
    rows_processed_in_epoch: int,
    total_rows_processed: int,
    best_avg_loss: float,
    args,
) -> None:
    checkpoint_path.parent.mkdir(parents=True, exist_ok=True)
    model_path.parent.mkdir(parents=True, exist_ok=True)

    safe_args = {
        key: str(value) if isinstance(value, Path) else value
        for key, value in vars(args).items()
    }

    raw_model = model._orig_mod if hasattr(model, "_orig_mod") else model
    state = {
        "model_state": raw_model.state_dict(),
        "optimizer_state": optimizer.state_dict(),
        "scheduler_state": scheduler.state_dict(),
        "next_epoch": next_epoch,
        "rows_processed_in_epoch": rows_processed_in_epoch,
        "total_rows_processed": total_rows_processed,
        "best_avg_loss": best_avg_loss,
        "args": safe_args,
        "saved_at": time.time(),
    }
    torch.save(state, checkpoint_path)
    torch.save(raw_model.state_dict(), model_path)


def load_training_state(
    checkpoint_path: Path,
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    scheduler,
    device: torch.device,
):
    state = torch.load(checkpoint_path, map_location=device, weights_only=False)
    model.load_state_dict(state["model_state"])
    optimizer.load_state_dict(state["optimizer_state"])
    scheduler.load_state_dict(state["scheduler_state"])
    return state


def main(argv=None) -> None:
    args = build_parser().parse_args(argv)

    if not args.csv.exists():
        print(f"CSV not found: {args.csv}", file=sys.stderr)
        raise SystemExit(1)
    if not args.mapping.exists():
        print(f"Move mapping not found: {args.mapping}", file=sys.stderr)
        raise SystemExit(1)

    move_list, move2idx = load_move_mapping(args.mapping)
    device = choose_device()
    batch_size = choose_batch_size(device, args.batch_size)
    amp_enabled = choose_amp(device, args.amp)

    print(
        f"Device: {device} | moves: {len(move_list)} | batch_size: {batch_size} | "
        f"chunk_size: {args.chunk_size} | amp: {amp_enabled} | compile: {args.compile_model}"
    )
    print(f"CSV: {args.csv}")
    sys.stdout.flush()

    model = ChessNet(len(move_list)).to(device)
    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=args.lr,
        weight_decay=args.weight_decay,
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=max(args.epochs, 1), eta_min=1e-5)
    criterion = nn.CrossEntropyLoss()

    start_epoch = 0
    resume_rows = 0
    total_rows_processed = 0
    best_avg_loss = float("inf")

    if args.resume and args.checkpoint_path.exists():
        state = load_training_state(args.checkpoint_path, model, optimizer, scheduler, device)
        start_epoch = int(state.get("next_epoch", 0))
        resume_rows = int(state.get("rows_processed_in_epoch", 0))
        total_rows_processed = int(state.get("total_rows_processed", 0))
        best_avg_loss = float(state.get("best_avg_loss", float("inf")))
        print(
            f"♻️ Resumed from checkpoint: epoch={start_epoch}, resume_rows={resume_rows}, "
            f"total_rows={total_rows_processed}"
        )
    elif args.model_path.exists():
        try:
            model.load_state_dict(torch.load(args.model_path, map_location=device))
            print(f"✅ Loaded existing DaniBot weights from {args.model_path}")
        except (RuntimeError, KeyError) as exc:
            print(f"⚠️ Could not load existing model weights: {exc}")

    if args.compile_model and hasattr(torch, "compile"):
        try:
            model = torch.compile(model)
            print("✅ torch.compile enabled")
        except Exception as exc:
            print(f"⚠️ torch.compile failed, continuing without it: {exc}")

    if amp_enabled and device.type == "cuda":
        autocast_ctx = lambda: torch.autocast(device_type="cuda", dtype=torch.float16)
        scaler = torch.amp.GradScaler("cuda", enabled=True) if hasattr(torch, "amp") else torch.cuda.amp.GradScaler(enabled=True)
    else:
        autocast_ctx = nullcontext
        scaler = torch.amp.GradScaler("cuda", enabled=False) if hasattr(torch, "amp") else torch.cuda.amp.GradScaler(enabled=False)

    for epoch in range(start_epoch, args.epochs):
        epoch_start = time.perf_counter()
        epoch_loss_sum = 0.0
        epoch_policy_sum = 0.0
        epoch_value_sum = 0.0
        epoch_correct = 0
        epoch_rows = 0
        chunk_idx = 0
        stats_snapshot = None
        skip_rows = resume_rows if epoch == start_epoch else 0
        rows_processed_this_epoch = skip_rows

        print(f"===== CSV EPOCH {epoch + 1}/{args.epochs} =====")
        sys.stdout.flush()

        for (x_chunk, y_chunk, v_chunk), stats_snapshot in iterate_csv_chunks(
            csv_path=args.csv,
            move2idx=move2idx,
            chunk_size=args.chunk_size,
            move_format=args.move_format,
            encoding=args.encoding,
            max_rows=args.max_rows,
            skip_valid_rows=skip_rows,
        ):
            chunk_idx += 1
            prep_start = time.perf_counter()
            num_samples = x_chunk.size(0)

            if device.type == "cuda":
                x_chunk = x_chunk.pin_memory()
                y_chunk = y_chunk.pin_memory()
                v_chunk = v_chunk.pin_memory()

            indices = torch.randperm(num_samples)
            prep_time = time.perf_counter() - prep_start
            train_start = time.perf_counter()
            chunk_loss_sum = 0.0
            chunk_policy_sum = 0.0
            chunk_value_sum = 0.0
            chunk_correct = 0

            model.train()
            for start in range(0, num_samples, batch_size):
                batch_indices = indices[start:start + batch_size]
                xb = x_chunk.index_select(0, batch_indices).to(device, non_blocking=(device.type == "cuda"))
                yb = y_chunk.index_select(0, batch_indices).to(device, non_blocking=(device.type == "cuda"))
                vb = v_chunk.index_select(0, batch_indices).to(device, non_blocking=(device.type == "cuda"))

                optimizer.zero_grad(set_to_none=True)
                with autocast_ctx():
                    output = model(xb)
                    if isinstance(output, tuple):
                        logits, value_pred = output
                    else:
                        logits, value_pred = output, None
                    policy_loss = criterion(logits, yb)
                    if value_pred is not None and args.value_weight > 0:
                        value_loss = nn.functional.mse_loss(value_pred.squeeze(-1), vb)
                        loss = policy_loss + args.value_weight * value_loss
                    else:
                        value_loss = torch.zeros((), device=device)
                        loss = policy_loss

                if scaler.is_enabled():
                    scaler.scale(loss).backward()
                    if args.grad_clip > 0:
                        scaler.unscale_(optimizer)
                        torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
                    scaler.step(optimizer)
                    scaler.update()
                else:
                    loss.backward()
                    if args.grad_clip > 0:
                        torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
                    optimizer.step()

                with torch.no_grad():
                    chunk_loss_sum += loss.item() * xb.size(0)
                    chunk_policy_sum += policy_loss.item() * xb.size(0)
                    chunk_value_sum += value_loss.item() * xb.size(0)
                    chunk_correct += logits.argmax(1).eq(yb).sum().item()

            train_time = time.perf_counter() - train_start
            epoch_loss_sum += chunk_loss_sum
            epoch_policy_sum += chunk_policy_sum
            epoch_value_sum += chunk_value_sum
            epoch_correct += chunk_correct
            epoch_rows += num_samples
            total_rows_processed += num_samples
            rows_processed_this_epoch += num_samples

            if args.progress_every_chunks > 0 and (chunk_idx % args.progress_every_chunks == 0):
                avg_loss = epoch_loss_sum / max(epoch_rows, 1)
                acc = 100.0 * epoch_correct / max(epoch_rows, 1)
                pos_per_sec = num_samples / max(train_time, 1e-9)
                print(
                    f"Chunk {chunk_idx} | Samples: {num_samples} | Prep: {prep_time:.2f}s | "
                    f"Train: {train_time:.2f}s ({pos_per_sec:.0f} pos/s) | "
                    f"Loss: {chunk_loss_sum / max(num_samples, 1):.4f} | "
                    f"Policy: {chunk_policy_sum / max(num_samples, 1):.4f} | "
                    f"Value: {chunk_value_sum / max(num_samples, 1):.4f} | "
                    f"Avg Loss: {avg_loss:.4f} | Acc: {acc:.1f}% | Rows: {epoch_rows}"
                )
                sys.stdout.flush()

            if args.checkpoint_every_chunks > 0 and (chunk_idx % args.checkpoint_every_chunks == 0):
                save_training_state(
                    checkpoint_path=args.checkpoint_path,
                    model_path=args.model_path,
                    model=model,
                    optimizer=optimizer,
                    scheduler=scheduler,
                    next_epoch=epoch,
                    rows_processed_in_epoch=rows_processed_this_epoch,
                    total_rows_processed=total_rows_processed,
                    best_avg_loss=best_avg_loss,
                    args=args,
                )
                print(f"💾 Checkpoint saved at chunk {chunk_idx}")
                sys.stdout.flush()

        scheduler.step()
        epoch_time = time.perf_counter() - epoch_start

        if epoch_rows == 0:
            print("No trainable rows were found in the CSV.")
            break

        avg_loss = epoch_loss_sum / epoch_rows
        avg_policy = epoch_policy_sum / epoch_rows
        avg_value = epoch_value_sum / epoch_rows
        acc = 100.0 * epoch_correct / epoch_rows
        best_avg_loss = min(best_avg_loss, avg_loss)

        print(
            f"Epoch {epoch + 1}/{args.epochs} | Avg Loss: {avg_loss:.4f} | "
            f"Policy: {avg_policy:.4f} | Value: {avg_value:.4f} | "
            f"Acc: {acc:.1f}% | Rows: {epoch_rows} | "
            f"Time: {epoch_time:.1f}s ({epoch_rows / max(epoch_time, 1e-9):.0f} pos/s)"
        )
        if stats_snapshot is not None:
            print(
                "CSV stats | "
                f"seen={stats_snapshot['csv_rows_seen']} | "
                f"valid={stats_snapshot['valid_rows_seen']} | "
                f"invalid_fen={stats_snapshot['invalid_fen']} | "
                f"invalid_move={stats_snapshot['invalid_move']} | "
                f"unmapped={stats_snapshot['unmapped_move']}"
            )
        sys.stdout.flush()

        save_training_state(
            checkpoint_path=args.checkpoint_path,
            model_path=args.model_path,
            model=model,
            optimizer=optimizer,
            scheduler=scheduler,
            next_epoch=epoch + 1,
            rows_processed_in_epoch=0,
            total_rows_processed=total_rows_processed,
            best_avg_loss=best_avg_loss,
            args=args,
        )
        print(f"💾 Epoch checkpoint + model saved → {args.model_path}")
        sys.stdout.flush()
        resume_rows = 0

    print(f"✅ CSV training complete. Model saved to {args.model_path}")


if __name__ == "__main__":
    main()

