#!/usr/bin/env python3
"""Train DaniBot directly from a FEN/Move CSV dataset.

The CSV is expected to contain columns:
  - FEN
  - Move
  - Result (optional; "1-0" / "0-1" / "1/2-1/2") — used as the value-head target

Move can be SAN or UCI. By default, the script auto-detects the format.
The current project CSVs generated by scripts/pgn_to_fen_move_csv.py are SAN,
so they work out of the box.

This trainer is designed for large CSV files and streams data chunk-by-chunk,
so it does not need to load the full dataset into memory. Chunks are produced on
a background thread and passed through a shuffle buffer, so consecutive batches
are not all drawn from the same game.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import queue
import random
import re
import sys
import threading
import time
from contextlib import nullcontext
from pathlib import Path
from typing import Optional

import chess
import numpy as np
import torch
import torch.nn as nn

from ArchiveAlpha import HAS_CYTHON_BATCH, cy_encode_board_batch, encode_board_array
from ChessNet import ChessNet


PROJECT_ROOT = Path(__file__).resolve().parent
CHECKPOINTS_DIR = PROJECT_ROOT / "checkpoints"
UCI_MOVE_RE = re.compile(r"^[a-h][1-8][a-h][1-8][qrbn]?$")
RESULT_VALUES = {"1-0": 1.0, "0-1": -1.0, "1/2-1/2": 0.0}


def detect_default_csv() -> Path:
    candidates = [
        PROJECT_ROOT / "lichess_2200plus_fen_move.csv",
        PROJECT_ROOT / "lichess_2500plus_fen_move.csv",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Train DaniBot from a streamed FEN/Move CSV dataset."
    )
    parser.add_argument("--csv", type=Path, default=detect_default_csv(), help="Input FEN/Move CSV path")
    parser.add_argument("--mapping", type=Path, default=PROJECT_ROOT / "move_mapping.json", help="move_mapping.json path")
    parser.add_argument("--model-path", type=Path, default=PROJECT_ROOT / "danibot.pth", help="Output DaniBot model path")
    parser.add_argument(
        "--checkpoint-path",
        type=Path,
        default=CHECKPOINTS_DIR / "danibot_csv_resume.pt",
        help="Resume checkpoint path",
    )
    parser.add_argument("--epochs", type=int, default=5, help="Number of epochs")
    parser.add_argument("--batch-size", type=int, default=None, help="Mini-batch size")
    parser.add_argument("--chunk-size", type=int, default=8192, help="CSV samples encoded per chunk")
    parser.add_argument("--lr", type=float, default=1e-3, help="Peak learning rate")
    parser.add_argument("--min-lr", type=float, default=1e-5, help="Final learning rate of the cosine decay")
    parser.add_argument("--warmup-steps", type=int, default=500, help="Linear LR warmup steps; 0 disables warmup")
    parser.add_argument(
        "--total-steps",
        type=int,
        default=None,
        help="Optimizer steps the cosine decay is spread over. Estimated from the CSV size when omitted.",
    )
    parser.add_argument("--weight-decay", type=float, default=1e-5, help="AdamW weight decay")
    parser.add_argument("--grad-clip", type=float, default=1.0, help="Gradient clipping norm; <=0 disables clipping")
    parser.add_argument("--label-smoothing", type=float, default=0.05, help="Policy cross-entropy label smoothing")
    parser.add_argument(
        "--move-format",
        choices=["auto", "san", "uci"],
        default="auto",
        help="How to parse the Move column",
    )
    parser.add_argument(
        "--value-weight",
        type=float,
        default=1.0,
        help="Weight of the value loss. Ignored (forced to 0) when the CSV has no Result column.",
    )
    parser.add_argument(
        "--legal-mask",
        dest="legal_mask",
        action="store_true",
        help="Mask illegal moves out of the policy softmax (matches inference; costs extra CPU)",
    )
    parser.add_argument("--no-legal-mask", dest="legal_mask", action="store_false")
    parser.add_argument(
        "--val-fraction",
        type=float,
        default=0.01,
        help="Fraction of whole games held out for validation; 0 disables validation",
    )
    parser.add_argument(
        "--val-max-rows",
        type=int,
        default=200_000,
        help="Cap on held-out positions evaluated per epoch",
    )
    parser.add_argument(
        "--shuffle-buffer",
        type=int,
        default=16,
        help="Chunks held in the reservoir used to decorrelate samples across games",
    )
    parser.add_argument("--prefetch", type=int, default=3, help="Chunks prefetched on the loader thread; 0 disables it")
    parser.add_argument("--seed", type=int, default=1234, help="RNG seed (also fixes the validation split)")
    parser.add_argument(
        "--max-rows",
        type=int,
        default=None,
        help="Optional limit of valid training rows per epoch (useful for smoke tests)",
    )
    parser.add_argument(
        "--checkpoint-every-chunks",
        type=int,
        default=50,
        help="Save checkpoint/model every N chunks",
    )
    parser.add_argument(
        "--progress-every-chunks",
        type=int,
        default=10,
        help="Print training progress every N chunks",
    )
    parser.add_argument("--encoding", default="utf-8", help="CSV file encoding")
    parser.add_argument("--resume", dest="resume", action="store_true", help="Resume from checkpoint if it exists")
    parser.add_argument("--no-resume", dest="resume", action="store_false", help="Ignore resume checkpoint")
    parser.add_argument("--amp", dest="amp", action="store_true", help="Enable AMP (default on CUDA; opt-in and usually slower on MPS)")
    parser.add_argument("--no-amp", dest="amp", action="store_false", help="Disable AMP")
    parser.add_argument("--compile", dest="compile_model", action="store_true", help="Enable torch.compile when available")
    parser.add_argument("--no-compile", dest="compile_model", action="store_false", help="Disable torch.compile")
    parser.set_defaults(resume=True, amp=None, compile_model=False, legal_mask=False)
    return parser


def choose_device() -> torch.device:
    if torch.backends.mps.is_available():
        return torch.device("mps")
    if torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")


def choose_batch_size(device: torch.device, explicit: Optional[int]) -> int:
    if explicit is not None:
        return explicit
    if device.type == "mps":
        return 384
    if device.type == "cuda":
        return 256
    return 128


def choose_amp(device: torch.device, explicit: Optional[bool]) -> bool:
    if explicit is not None:
        return explicit
    # Measured on this project's net: MPS bf16 autocast is ~35% *slower* than fp32,
    # so it stays opt-in via --amp. CUDA fp16 is a clear win.
    return device.type == "cuda"


def make_autocast(device: torch.device, enabled: bool):
    """Return (autocast_factory, grad_scaler). Only CUDA fp16 needs loss scaling."""
    if not enabled or device.type == "cpu":
        return nullcontext, torch.amp.GradScaler("cuda", enabled=False)
    if device.type == "cuda":
        return (
            lambda: torch.autocast(device_type="cuda", dtype=torch.float16),
            torch.amp.GradScaler("cuda", enabled=True),
        )
    # MPS: bf16 autocast, no scaler needed.
    return (
        lambda: torch.autocast(device_type="mps", dtype=torch.bfloat16),
        torch.amp.GradScaler("cuda", enabled=False),
    )


def lr_at_step(step: int, args) -> float:
    """Linear warmup then cosine decay, evaluated per optimizer step."""
    if args.warmup_steps > 0 and step < args.warmup_steps:
        return args.lr * (step + 1) / args.warmup_steps
    total = max(args.total_steps, args.warmup_steps + 1)
    progress = (step - args.warmup_steps) / max(total - args.warmup_steps, 1)
    progress = min(max(progress, 0.0), 1.0)
    return args.min_lr + 0.5 * (args.lr - args.min_lr) * (1.0 + math.cos(math.pi * progress))


def load_move_mapping(mapping_path: Path) -> tuple[list[str], dict[str, int]]:
    with mapping_path.open("r", encoding="utf-8") as f:
        move_list = json.load(f)
    return move_list, {uci: idx for idx, uci in enumerate(move_list)}


def parse_csv_move(board: chess.Board, move_text: str, move_format: str) -> chess.Move:
    move_text = move_text.strip()

    if move_format in ("auto", "uci") and UCI_MOVE_RE.match(move_text):
        move = chess.Move.from_uci(move_text)
        if move in board.legal_moves:
            return move
        if move_format == "uci":
            raise ValueError(f"Illegal UCI move for board: {move_text}")

    if move_format in ("auto", "san"):
        try:
            return board.parse_san(move_text)
        except ValueError:
            if move_format == "san":
                raise

    raise ValueError(f"Could not parse move '{move_text}' as {move_format}")


def validate_csv_columns(fieldnames) -> None:
    required = {"FEN", "Move"}
    actual = set(fieldnames or [])
    if not required.issubset(actual):
        missing = ", ".join(sorted(required - actual))
        print(f"CSV is missing required columns: {missing}", file=sys.stderr)
        raise SystemExit(1)


def csv_has_result_column(csv_path: Path, encoding: str) -> bool:
    with csv_path.open("r", newline="", encoding=encoding, errors="replace") as f:
        reader = csv.DictReader(f)
        return "Result" in (reader.fieldnames or [])


def fen_ply(fen: str) -> int:
    """Half-move number of a FEN, used to spot game boundaries in the CSV.

    We cannot key on the start position: the CSVs are run through
    dedupe_fen_move_csv.py, which leaves exactly one copy of it in the whole file.
    Within a game the ply only ever increases, so a ply that does not advance
    means a new game started. Dedup can drop positions mid-game, which only ever
    skips ply forward, so this stays correct.
    """
    parts = fen.split(" ")
    if len(parts) < 6:
        return -1
    try:
        fullmove = int(parts[5])
    except ValueError:
        return -1
    return 2 * (fullmove - 1) + (0 if parts[1] == "w" else 1)


def game_is_validation(game_id: int, seed: int, val_fraction: float) -> bool:
    if val_fraction <= 0.0:
        return False
    # Deterministic per-game hash so the split is stable across epochs and runs.
    h = (game_id * 2654435761 + seed * 40503) & 0xFFFFFFFF
    return (h / 0x100000000) < val_fraction


def build_chunk_tensors(
    boards: list[chess.Board],
    labels: list[int],
    values: list[float],
    move2idx: dict[str, int],
    n_moves: int,
    legal_mask: bool,
):
    if HAS_CYTHON_BATCH:
        x_np = cy_encode_board_batch(boards)
    else:
        x_np = np.stack([encode_board_array(board) for board in boards], axis=0)

    y_np = np.asarray(labels, dtype=np.int64)
    v_np = np.asarray(values, dtype=np.float32)

    tensors = [torch.from_numpy(x_np), torch.from_numpy(y_np), torch.from_numpy(v_np)]

    if legal_mask:
        mask_np = np.zeros((len(boards), n_moves), dtype=bool)
        for i, board in enumerate(boards):
            for move in board.legal_moves:
                idx = move2idx.get(move.uci())
                if idx is not None:
                    mask_np[i, idx] = True
        tensors.append(torch.from_numpy(mask_np))
    else:
        tensors.append(None)

    return tuple(tensors)


def iterate_csv_chunks(
    csv_path: Path,
    move2idx: dict[str, int],
    n_moves: int,
    chunk_size: int,
    move_format: str,
    encoding: str,
    max_rows: Optional[int],
    skip_valid_rows: int,
    split: str,
    val_fraction: float,
    seed: int,
    use_result: bool,
    legal_mask: bool,
):
    """Stream one split ("train" or "val") of the CSV as encoded chunks.

    Games are delimited by rows whose FEN is the starting position, and each game
    is assigned to exactly one split, so no position from a validation game is
    ever trained on.
    """
    stats = {
        "csv_rows_seen": 0,
        "valid_rows_seen": 0,
        "invalid_fen": 0,
        "invalid_move": 0,
        "unmapped_move": 0,
        "games_seen": 0,
    }

    with csv_path.open("r", newline="", encoding=encoding, errors="replace") as f:
        reader = csv.DictReader(f)
        validate_csv_columns(reader.fieldnames)

        boards: list[chess.Board] = []
        labels: list[int] = []
        values: list[float] = []
        game_id = -1
        prev_ply = -1
        skip_game = False

        for row in reader:
            stats["csv_rows_seen"] += 1

            fen = (row.get("FEN") or "").strip()
            move_text = (row.get("Move") or "").strip()
            if not fen or not move_text:
                stats["invalid_move"] += 1
                continue

            ply = fen_ply(fen)
            if ply <= prev_ply:
                game_id += 1
                stats["games_seen"] += 1
                in_val = game_is_validation(game_id, seed, val_fraction)
                skip_game = in_val if split == "train" else not in_val
            prev_ply = ply

            if skip_game:
                continue

            try:
                board = chess.Board(fen)
            except ValueError:
                stats["invalid_fen"] += 1
                continue

            try:
                move = parse_csv_move(board, move_text, move_format)
            except ValueError:
                stats["invalid_move"] += 1
                continue

            move_idx = move2idx.get(move.uci())
            if move_idx is None:
                stats["unmapped_move"] += 1
                continue

            stats["valid_rows_seen"] += 1

            if stats["valid_rows_seen"] <= skip_valid_rows:
                continue

            if max_rows is not None and (stats["valid_rows_seen"] - skip_valid_rows) > max_rows:
                break

            if use_result:
                result = (row.get("Result") or "").strip()
                value = RESULT_VALUES.get(result, 0.0)
                # Value target is from the perspective of the side to move.
                if board.turn == chess.BLACK:
                    value = -value
            else:
                value = 0.0

            boards.append(board)
            labels.append(move_idx)
            values.append(value)

            if len(labels) >= chunk_size:
                yield build_chunk_tensors(boards, labels, values, move2idx, n_moves, legal_mask), stats.copy()
                boards, labels, values = [], [], []

        if labels:
            yield build_chunk_tensors(boards, labels, values, move2idx, n_moves, legal_mask), stats.copy()


def prefetch(iterable, depth: int):
    """Run `iterable` on a background thread so encoding overlaps with training."""
    if depth <= 0:
        yield from iterable
        return

    q: queue.Queue = queue.Queue(maxsize=depth)
    sentinel = object()

    def worker():
        try:
            for item in iterable:
                q.put(item)
        except BaseException as exc:  # surfaced on the consumer thread
            q.put(exc)
        finally:
            q.put(sentinel)

    thread = threading.Thread(target=worker, daemon=True)
    thread.start()
    try:
        while True:
            item = q.get()
            if item is sentinel:
                return
            if isinstance(item, BaseException):
                raise item
            yield item
    finally:
        # Drain so the worker can exit if the consumer stopped early.
        while thread.is_alive():
            try:
                if q.get(timeout=0.1) is sentinel:
                    break
            except queue.Empty:
                pass


def shuffled_chunks(chunk_iter, buffer_chunks: int, rng: random.Random):
    """Reservoir over several chunks so a batch mixes positions from many games."""
    if buffer_chunks <= 1:
        yield from chunk_iter
        return

    buffer: list = []
    for payload in chunk_iter:
        buffer.append(payload)
        if len(buffer) >= buffer_chunks:
            idx = rng.randrange(len(buffer))
            buffer[idx], buffer[-1] = buffer[-1], buffer[idx]
            yield buffer.pop()
    rng.shuffle(buffer)
    yield from buffer


def split_policy_loss(logits, targets, mask, label_smoothing, criterion):
    """Cross-entropy, restricted to legal moves when a mask is supplied.

    With a mask we cannot hand -inf logits to nn.CrossEntropyLoss: label smoothing
    puts weight on every class, so the illegal ones make the loss inf. Instead the
    smoothing mass is spread over the legal moves only, which is also what we want
    it to mean here.
    """
    if mask is None:
        return criterion(logits, targets)

    log_probs = torch.log_softmax(logits.masked_fill(~mask, float("-inf")), dim=1)
    target_lp = log_probs.gather(1, targets.unsqueeze(1)).squeeze(1)
    if label_smoothing <= 0:
        return -target_lp.mean()

    n_legal = mask.sum(dim=1).clamp(min=1)
    legal_lp = log_probs.masked_fill(~mask, 0.0).sum(dim=1) / n_legal
    return -((1.0 - label_smoothing) * target_lp + label_smoothing * legal_lp).mean()


@torch.no_grad()
def evaluate(model, device, args, move2idx, n_moves, criterion, batch_size, use_result):
    """Policy/value metrics on held-out games."""
    model.eval()
    totals = {"rows": 0, "loss": 0.0, "policy": 0.0, "value": 0.0, "top1": 0, "top5": 0}

    chunks = iterate_csv_chunks(
        csv_path=args.csv,
        move2idx=move2idx,
        n_moves=n_moves,
        chunk_size=args.chunk_size,
        move_format=args.move_format,
        encoding=args.encoding,
        max_rows=args.val_max_rows,
        skip_valid_rows=0,
        split="val",
        val_fraction=args.val_fraction,
        seed=args.seed,
        use_result=use_result,
        legal_mask=args.legal_mask,
    )

    for (x_chunk, y_chunk, v_chunk, mask_chunk), _ in prefetch(chunks, args.prefetch):
        for start in range(0, x_chunk.size(0), batch_size):
            end = start + batch_size
            xb = x_chunk[start:end].to(device)
            yb = y_chunk[start:end].to(device)
            vb = v_chunk[start:end].to(device)
            mb = mask_chunk[start:end].to(device) if mask_chunk is not None else None

            logits, value_pred = model(xb)
            policy_loss = split_policy_loss(logits, yb, mb, args.label_smoothing, criterion)
            value_loss = nn.functional.mse_loss(value_pred.squeeze(-1), vb)
            loss = policy_loss + (args.value_weight * value_loss if use_result else 0.0)

            n = xb.size(0)
            totals["rows"] += n
            totals["loss"] += loss.item() * n
            totals["policy"] += policy_loss.item() * n
            totals["value"] += value_loss.item() * n
            scored = logits if mb is None else logits.masked_fill(~mb, float("-inf"))
            totals["top1"] += scored.argmax(1).eq(yb).sum().item()
            top5 = scored.topk(min(5, scored.size(1)), dim=1).indices
            totals["top5"] += top5.eq(yb.unsqueeze(1)).any(dim=1).sum().item()

    model.train()
    rows = max(totals["rows"], 1)
    return {
        "rows": totals["rows"],
        "loss": totals["loss"] / rows,
        "policy": totals["policy"] / rows,
        "value": totals["value"] / rows,
        "top1": 100.0 * totals["top1"] / rows,
        "top5": 100.0 * totals["top5"] / rows,
    }


def save_training_state(
    checkpoint_path: Path,
    model_path: Path,
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    next_epoch: int,
    rows_processed_in_epoch: int,
    total_rows_processed: int,
    global_step: int,
    best_val_loss: float,
    args,
) -> None:
    checkpoint_path.parent.mkdir(parents=True, exist_ok=True)
    model_path.parent.mkdir(parents=True, exist_ok=True)

    safe_args = {
        key: str(value) if isinstance(value, Path) else value
        for key, value in vars(args).items()
    }

    raw_model = model._orig_mod if hasattr(model, "_orig_mod") else model
    state = {
        "model_state": raw_model.state_dict(),
        "optimizer_state": optimizer.state_dict(),
        "next_epoch": next_epoch,
        "rows_processed_in_epoch": rows_processed_in_epoch,
        "total_rows_processed": total_rows_processed,
        "global_step": global_step,
        "best_val_loss": best_val_loss,
        "args": safe_args,
        "saved_at": time.time(),
    }
    torch.save(state, checkpoint_path)
    torch.save(raw_model.state_dict(), model_path)


def load_training_state(
    checkpoint_path: Path,
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    device: torch.device,
):
    state = torch.load(checkpoint_path, map_location=device, weights_only=False)
    model.load_state_dict(state["model_state"])
    optimizer.load_state_dict(state["optimizer_state"])
    return state


def estimate_total_steps(csv_path: Path, args, batch_size: int) -> int:
    """Rough optimizer-step budget for the cosine schedule, from the CSV byte size."""
    if args.max_rows is not None:
        rows_per_epoch = args.max_rows
    else:
        # ~80 bytes per FEN/Move row; only used to shape the LR curve.
        rows_per_epoch = max(int(csv_path.stat().st_size / 80), batch_size)
        rows_per_epoch = int(rows_per_epoch * (1.0 - args.val_fraction))
    return max(int(rows_per_epoch * args.epochs / batch_size), 1)


def main(argv=None) -> None:
    args = build_parser().parse_args(argv)

    if not args.csv.exists():
        print(f"CSV not found: {args.csv}", file=sys.stderr)
        raise SystemExit(1)
    if not args.mapping.exists():
        print(f"Move mapping not found: {args.mapping}", file=sys.stderr)
        raise SystemExit(1)

    torch.manual_seed(args.seed)
    rng = random.Random(args.seed)

    move_list, move2idx = load_move_mapping(args.mapping)
    n_moves = len(move_list)
    device = choose_device()
    batch_size = choose_batch_size(device, args.batch_size)
    amp_enabled = choose_amp(device, args.amp)
    use_result = csv_has_result_column(args.csv, args.encoding)

    if not use_result and args.value_weight > 0:
        print(
            "⚠️ CSV has no Result column — value head disabled for this run. "
            "Regenerate the CSV with a Result column to train it "
            "(training it against all-zero targets teaches the net that every position is a draw)."
        )
        args.value_weight = 0.0

    if args.total_steps is None:
        args.total_steps = estimate_total_steps(args.csv, args, batch_size)
    # A warmup longer than the run would mean the LR never decays at all.
    args.warmup_steps = min(args.warmup_steps, max(args.total_steps // 10, 1))
    # Keep smoke runs (--max-rows) from spending all their time in validation.
    if args.max_rows is not None:
        args.val_max_rows = min(args.val_max_rows, args.max_rows)

    print(
        f"Device: {device} | moves: {n_moves} | batch_size: {batch_size} | "
        f"chunk_size: {args.chunk_size} | amp: {amp_enabled} | compile: {args.compile_model}"
    )
    print(
        f"CSV: {args.csv} | value_head: {'on' if use_result else 'off'} | "
        f"legal_mask: {args.legal_mask} | val_fraction: {args.val_fraction} | "
        f"shuffle_buffer: {args.shuffle_buffer} chunks | prefetch: {args.prefetch} | "
        f"lr: {args.lr}→{args.min_lr} over ~{args.total_steps} steps (warmup {args.warmup_steps})"
    )
    sys.stdout.flush()

    model = ChessNet(n_moves).to(device)
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=args.lr,
        weight_decay=args.weight_decay,
    )
    criterion = nn.CrossEntropyLoss(label_smoothing=args.label_smoothing)

    start_epoch = 0
    resume_rows = 0
    total_rows_processed = 0
    global_step = 0
    best_val_loss = float("inf")
    best_model_path = args.model_path.with_name(args.model_path.stem + "_best" + args.model_path.suffix)

    if args.resume and args.checkpoint_path.exists():
        state = load_training_state(args.checkpoint_path, model, optimizer, device)
        start_epoch = int(state.get("next_epoch", 0))
        resume_rows = int(state.get("rows_processed_in_epoch", 0))
        total_rows_processed = int(state.get("total_rows_processed", 0))
        global_step = int(state.get("global_step", 0))
        best_val_loss = float(state.get("best_val_loss", float("inf")))
        print(
            f"♻️ Resumed from checkpoint: epoch={start_epoch}, resume_rows={resume_rows}, "
            f"total_rows={total_rows_processed}, step={global_step}"
        )
    elif args.model_path.exists():
        try:
            model.load_state_dict(torch.load(args.model_path, map_location=device))
            print(f"✅ Loaded existing DaniBot weights from {args.model_path}")
        except (RuntimeError, KeyError) as exc:
            print(f"⚠️ Could not load existing model weights: {exc}")

    if args.compile_model and hasattr(torch, "compile"):
        try:
            model = torch.compile(model)
            print("✅ torch.compile enabled")
        except Exception as exc:
            print(f"⚠️ torch.compile failed, continuing without it: {exc}")

    autocast_ctx, scaler = make_autocast(device, amp_enabled)

    for epoch in range(start_epoch, args.epochs):
        epoch_start = time.perf_counter()
        epoch_loss_sum = 0.0
        epoch_policy_sum = 0.0
        epoch_value_sum = 0.0
        epoch_correct = 0
        epoch_rows = 0
        chunk_idx = 0
        stats_snapshot = None
        # Chunks come out of the shuffle buffer out of order, so track the furthest
        # snapshot rather than whichever one happened to be yielded last.
        best_stats = None
        skip_rows = resume_rows if epoch == start_epoch else 0
        rows_processed_this_epoch = skip_rows

        print(f"===== CSV EPOCH {epoch + 1}/{args.epochs} =====")
        sys.stdout.flush()

        chunks = iterate_csv_chunks(
            csv_path=args.csv,
            move2idx=move2idx,
            n_moves=n_moves,
            chunk_size=args.chunk_size,
            move_format=args.move_format,
            encoding=args.encoding,
            max_rows=args.max_rows,
            skip_valid_rows=skip_rows,
            split="train",
            val_fraction=args.val_fraction,
            seed=args.seed,
            use_result=use_result,
            legal_mask=args.legal_mask,
        )
        chunks = shuffled_chunks(prefetch(chunks, args.prefetch), args.shuffle_buffer, rng)

        model.train()
        for (x_chunk, y_chunk, v_chunk, mask_chunk), stats_snapshot in chunks:
            chunk_idx += 1
            if best_stats is None or stats_snapshot["csv_rows_seen"] > best_stats["csv_rows_seen"]:
                best_stats = stats_snapshot
            prep_start = time.perf_counter()
            num_samples = x_chunk.size(0)

            if device.type == "cuda":
                x_chunk = x_chunk.pin_memory()
                y_chunk = y_chunk.pin_memory()
                v_chunk = v_chunk.pin_memory()
                if mask_chunk is not None:
                    mask_chunk = mask_chunk.pin_memory()

            indices = torch.randperm(num_samples)
            prep_time = time.perf_counter() - prep_start
            train_start = time.perf_counter()
            chunk_loss_sum = 0.0
            chunk_policy_sum = 0.0
            chunk_value_sum = 0.0
            chunk_correct = 0

            non_blocking = device.type == "cuda"
            for start in range(0, num_samples, batch_size):
                batch_indices = indices[start:start + batch_size]
                xb = x_chunk.index_select(0, batch_indices).to(device, non_blocking=non_blocking)
                yb = y_chunk.index_select(0, batch_indices).to(device, non_blocking=non_blocking)
                vb = v_chunk.index_select(0, batch_indices).to(device, non_blocking=non_blocking)
                mb = (
                    mask_chunk.index_select(0, batch_indices).to(device, non_blocking=non_blocking)
                    if mask_chunk is not None
                    else None
                )

                lr = lr_at_step(global_step, args)
                for group in optimizer.param_groups:
                    group["lr"] = lr

                optimizer.zero_grad(set_to_none=True)
                with autocast_ctx():
                    logits, value_pred = model(xb)
                    policy_loss = split_policy_loss(logits, yb, mb, args.label_smoothing, criterion)
                    if args.value_weight > 0:
                        value_loss = nn.functional.mse_loss(value_pred.squeeze(-1), vb)
                        loss = policy_loss + args.value_weight * value_loss
                    else:
                        value_loss = torch.zeros((), device=device)
                        loss = policy_loss

                if scaler.is_enabled():
                    scaler.scale(loss).backward()
                    if args.grad_clip > 0:
                        scaler.unscale_(optimizer)
                        torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
                    scaler.step(optimizer)
                    scaler.update()
                else:
                    loss.backward()
                    if args.grad_clip > 0:
                        torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
                    optimizer.step()

                global_step += 1

                with torch.no_grad():
                    chunk_loss_sum += loss.item() * xb.size(0)
                    chunk_policy_sum += policy_loss.item() * xb.size(0)
                    chunk_value_sum += value_loss.item() * xb.size(0)
                    scored = logits if mb is None else logits.masked_fill(~mb, float("-inf"))
                    chunk_correct += scored.argmax(1).eq(yb).sum().item()

            train_time = time.perf_counter() - train_start
            epoch_loss_sum += chunk_loss_sum
            epoch_policy_sum += chunk_policy_sum
            epoch_value_sum += chunk_value_sum
            epoch_correct += chunk_correct
            epoch_rows += num_samples
            total_rows_processed += num_samples
            rows_processed_this_epoch += num_samples

            if args.progress_every_chunks > 0 and (chunk_idx % args.progress_every_chunks == 0):
                avg_loss = epoch_loss_sum / max(epoch_rows, 1)
                acc = 100.0 * epoch_correct / max(epoch_rows, 1)
                pos_per_sec = num_samples / max(train_time, 1e-9)
                print(
                    f"Chunk {chunk_idx} | Samples: {num_samples} | Prep: {prep_time:.2f}s | "
                    f"Train: {train_time:.2f}s ({pos_per_sec:.0f} pos/s) | "
                    f"LR: {lr_at_step(global_step, args):.2e} | "
                    f"Loss: {chunk_loss_sum / max(num_samples, 1):.4f} | "
                    f"Policy: {chunk_policy_sum / max(num_samples, 1):.4f} | "
                    f"Value: {chunk_value_sum / max(num_samples, 1):.4f} | "
                    f"Avg Loss: {avg_loss:.4f} | Acc: {acc:.1f}% | Rows: {epoch_rows}"
                )
                sys.stdout.flush()

            if args.checkpoint_every_chunks > 0 and (chunk_idx % args.checkpoint_every_chunks == 0):
                save_training_state(
                    checkpoint_path=args.checkpoint_path,
                    model_path=args.model_path,
                    model=model,
                    optimizer=optimizer,
                    next_epoch=epoch,
                    rows_processed_in_epoch=rows_processed_this_epoch,
                    total_rows_processed=total_rows_processed,
                    global_step=global_step,
                    best_val_loss=best_val_loss,
                    args=args,
                )
                print(f"💾 Checkpoint saved at chunk {chunk_idx}")
                sys.stdout.flush()

        epoch_time = time.perf_counter() - epoch_start

        if epoch_rows == 0:
            print("No trainable rows were found in the CSV.")
            break

        avg_loss = epoch_loss_sum / epoch_rows
        avg_policy = epoch_policy_sum / epoch_rows
        avg_value = epoch_value_sum / epoch_rows
        acc = 100.0 * epoch_correct / epoch_rows

        print(
            f"Epoch {epoch + 1}/{args.epochs} | Avg Loss: {avg_loss:.4f} | "
            f"Policy: {avg_policy:.4f} | Value: {avg_value:.4f} | "
            f"Acc: {acc:.1f}% | Rows: {epoch_rows} | "
            f"Time: {epoch_time:.1f}s ({epoch_rows / max(epoch_time, 1e-9):.0f} pos/s)"
        )
        stats_snapshot = best_stats
        if stats_snapshot is not None:
            print(
                "CSV stats | "
                f"seen={stats_snapshot['csv_rows_seen']} | "
                f"games={stats_snapshot['games_seen']} | "
                f"valid={stats_snapshot['valid_rows_seen']} | "
                f"invalid_fen={stats_snapshot['invalid_fen']} | "
                f"invalid_move={stats_snapshot['invalid_move']} | "
                f"unmapped={stats_snapshot['unmapped_move']}"
            )
        sys.stdout.flush()

        if args.val_fraction > 0:
            val_start = time.perf_counter()
            metrics = evaluate(model, device, args, move2idx, n_moves, criterion, batch_size, use_result)
            print(
                f"Validation | Loss: {metrics['loss']:.4f} | Policy: {metrics['policy']:.4f} | "
                f"Value: {metrics['value']:.4f} | Top-1: {metrics['top1']:.1f}% | "
                f"Top-5: {metrics['top5']:.1f}% | Rows: {metrics['rows']} | "
                f"Time: {time.perf_counter() - val_start:.1f}s"
            )
            gap = acc - metrics["top1"]
            if gap > 5.0:
                print(f"⚠️ Train/val top-1 gap is {gap:.1f}pp — the model is starting to memorize.")
            if metrics["rows"] > 0 and metrics["loss"] < best_val_loss:
                best_val_loss = metrics["loss"]
                raw_model = model._orig_mod if hasattr(model, "_orig_mod") else model
                torch.save(raw_model.state_dict(), best_model_path)
                print(f"🏆 New best validation loss — saved {best_model_path.name}")
            sys.stdout.flush()

        save_training_state(
            checkpoint_path=args.checkpoint_path,
            model_path=args.model_path,
            model=model,
            optimizer=optimizer,
            next_epoch=epoch + 1,
            rows_processed_in_epoch=0,
            total_rows_processed=total_rows_processed,
            global_step=global_step,
            best_val_loss=best_val_loss,
            args=args,
        )
        print(f"💾 Epoch checkpoint + model saved → {args.model_path}")
        sys.stdout.flush()
        resume_rows = 0

    print(f"✅ CSV training complete. Model saved to {args.model_path}")
    if args.val_fraction > 0 and best_val_loss < float("inf"):
        print(f"   Best validation loss {best_val_loss:.4f} → {best_model_path}")


if __name__ == "__main__":
    main()
